### ISSUE TITLE
Timer1 hangs delay() function.

### ISSUE THREAD

**Issue by Divino-Fire** [PaulStoffregen/TimerOne#51]
I am using an arduino nano
When I use timer1 library, the delay() function belonging to timer 0 hangs the entire code execution.

**Comment by PaulStoffregen** [comment]
Maybe you're calling delay() inside an interrupt function?  Just a blind guess, since I can't see your code.

If you believe the TimerOne library has a bug, you must show a complete program to clearly reproduce the problem.  No investigation will happen without a program which can be copied into Arduino and run on a similar board to recreate the problem.
